### ISSUE TITLE
plugin's modification to make it compatible with ignition gazebo 

### ISSUE THREAD

**Issue by addy1997** [pal-robotics/pal_gazebo_plugins#12]
Hi,

Since these plugins aren't supported by the [ignition gazebo](https://ignitionrobotics.org/home), I wanted to modify these plugins for my application. I had the following queries:

1. How to obtain a license to modify these for personal use?
2. Are the Pal robots supported in the ignition gazebo?

Thanks

**Comment by saikishor** [comment]
Hello @addy1997,

Thanks for showing interest in our plugins. 

1. As the packages states in the `package.xml`, the license is BSD. So, you can free to modify the package for personal use, however, you have to retain the original copyrights inside the files.
2. Right now, they are not migrated to ignition gazebo, but probably we will be working to migrate them in near future.

**Comment by addy1997** [comment]
Thanks, @saikishor for clarifying. I will retain the license as given in the `package.xml`.
