### ISSUE TITLE
Lack off version  'reemc-sim-0.2'

### ISSUE THREAD

**Issue by SkyCloudShang** [pal-robotics/pal_gazebo_plugins#8]
![image](https://user-images.githubusercontent.com/8363142/34913205-b642aa48-f931-11e7-87e3-6f705d523664.png)

# PAL packages
- git: {local-name: pal_gazebo_plugins, uri: 'https://github.com/pal-robotics/pal_gazebo_plugins.git', version: 'reemc-sim-0.2'}

In the  "https://raw.githubusercontent.com/pal-robotics/pal-ros-pkg/master/reemc-sim-hydro.rosinstall "
there seems to have the version 'reemc-sim-0.2',however, I can not find this version from github. Thus I get some make problems in Using REEMC Simulation. How can I deal with this version bug.

**Comment by SkyCloudShang** [comment]
CMake Warning at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:76 (find_package):
  Could not find a package configuration file provided by "humanoid_nav_msgs"
  with any of the following names:

    humanoid_nav_msgsConfig.cmake
    humanoid_nav_msgs-config.cmake

  Add the installation prefix of "humanoid_nav_msgs" to CMAKE_PREFIX_PATH or
  set "humanoid_nav_msgs_DIR" to a directory containing one of the above
  files.  If "humanoid_nav_msgs" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  pal_msgs/pal_walking_msgs/CMakeLists.txt:4 (find_package)


-- Could not find the required component 'humanoid_nav_msgs'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "humanoid_nav_msgs"
  with any of the following names:

    humanoid_nav_msgsConfig.cmake
    humanoid_nav_msgs-config.cmake

  Add the installation prefix of "humanoid_nav_msgs" to CMAKE_PREFIX_PATH or
  set "humanoid_nav_msgs_DIR" to a directory containing one of the above
  files.  If "humanoid_nav_msgs" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  pal_msgs/pal_walking_msgs/CMakeLists.txt:4 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/syf/reemc-sim_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/syf/reemc-sim_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed

**Comment by v-lopez** [comment]
Hi @SkyCloudShang I have added back the missing tag reemc-sim-0.2.

The second problem you have is that you have not installed ros-hydro-humanoid-nav-msgs , or the version in the ROS distro you are using.
